user:
  name:
    max_length: 50

  email:
    max_length: 50

  password:
    min_length: 6

  per_page: 10

user_helper:
  size: 80

session:
  remember: "1"

post:
  per_page: 10

avar_comment:
  size: 50

avar_index:
  size: 60
